# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/authleague.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.layoutP1P2 = QtWidgets.QVBoxLayout()
        self.layoutP1P2.setObjectName("layoutP1P2")
        self.widgetLayoutP1 = QtWidgets.QWidget(Form)
        self.widgetLayoutP1.setObjectName("widgetLayoutP1")
        self.layoutP1 = QtWidgets.QHBoxLayout(self.widgetLayoutP1)
        self.layoutP1.setObjectName("layoutP1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.img = QtWidgets.QWidget(self.widgetLayoutP1)
        self.img.setMinimumSize(QtCore.QSize(300, 300))
        self.img.setStyleSheet("border-image: url(:/ui/img/placeholder_head.jpg);")
        self.img.setObjectName("img")
        self.horizontalLayout_5.addWidget(self.img)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.lblName = QtWidgets.QLabel(self.widgetLayoutP1)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblName.setFont(font)
        self.lblName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblName.setObjectName("lblName")
        self.verticalLayout_3.addWidget(self.lblName)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.lblStat1 = QtWidgets.QLabel(self.widgetLayoutP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblStat1.sizePolicy().hasHeightForWidth())
        self.lblStat1.setSizePolicy(sizePolicy)
        self.lblStat1.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblStat1.setFont(font)
        self.lblStat1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblStat1.setWordWrap(True)
        self.lblStat1.setObjectName("lblStat1")
        self.verticalLayout_3.addWidget(self.lblStat1)
        self.lblStat2 = QtWidgets.QLabel(self.widgetLayoutP1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblStat2.setFont(font)
        self.lblStat2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblStat2.setObjectName("lblStat2")
        self.verticalLayout_3.addWidget(self.lblStat2)
        self.lblStat3 = QtWidgets.QLabel(self.widgetLayoutP1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lblStat3.setFont(font)
        self.lblStat3.setObjectName("lblStat3")
        self.verticalLayout_3.addWidget(self.lblStat3)
        self.layoutP1.addLayout(self.verticalLayout_3)
        self.layoutP1P2.addWidget(self.widgetLayoutP1)
        self.horizontalLayout.addLayout(self.layoutP1P2)
        spacerItem4 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        spacerItem5 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.playersList = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.playersList.setFont(font)
        self.playersList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.playersList.setAutoScroll(True)
        self.playersList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.playersList.setProperty("showDropIndicator", False)
        self.playersList.setAlternatingRowColors(True)
        self.playersList.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.playersList.setObjectName("playersList")
        self.horizontalLayout.addWidget(self.playersList)
        spacerItem6 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Identify yourselves! "))
        self.label_6.setText(_translate("Form", "Use the table\'s RFID reader with your card."))
        self.lblName.setText(_translate("Form", "Name"))
        self.lblStat1.setText(_translate("Form", "Stat"))
        self.lblStat2.setText(_translate("Form", "Stat"))
        self.lblStat3.setText(_translate("Form", "Stat"))
from babyfut_server.ui import assets_rc
