# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/authquick.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.layoutP1P2 = QtWidgets.QVBoxLayout()
        self.layoutP1P2.setObjectName("layoutP1P2")
        self.widgetLayoutP1 = QtWidgets.QWidget(Form)
        self.widgetLayoutP1.setObjectName("widgetLayoutP1")
        self.layoutP1 = QtWidgets.QHBoxLayout(self.widgetLayoutP1)
        self.layoutP1.setObjectName("layoutP1")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutP1.addItem(spacerItem2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.imgP1 = QtWidgets.QWidget(self.widgetLayoutP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgP1.sizePolicy().hasHeightForWidth())
        self.imgP1.setSizePolicy(sizePolicy)
        self.imgP1.setMinimumSize(QtCore.QSize(200, 200))
        self.imgP1.setMaximumSize(QtCore.QSize(200, 200))
        self.imgP1.setStyleSheet("border-image: url(:/ui/img/placeholder_head.jpg);")
        self.imgP1.setObjectName("imgP1")
        self.horizontalLayout_5.addWidget(self.imgP1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.lblP1 = QtWidgets.QLabel(self.widgetLayoutP1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblP1.sizePolicy().hasHeightForWidth())
        self.lblP1.setSizePolicy(sizePolicy)
        self.lblP1.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblP1.setFont(font)
        self.lblP1.setAlignment(QtCore.Qt.AlignCenter)
        self.lblP1.setWordWrap(True)
        self.lblP1.setObjectName("lblP1")
        self.verticalLayout_3.addWidget(self.lblP1)
        self.layoutP1.addLayout(self.verticalLayout_3)
        self.layoutP1P2.addWidget(self.widgetLayoutP1)
        self.widgetLayoutP2 = QtWidgets.QWidget(Form)
        self.widgetLayoutP2.setObjectName("widgetLayoutP2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetLayoutP2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.imgP2 = QtWidgets.QWidget(self.widgetLayoutP2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgP2.sizePolicy().hasHeightForWidth())
        self.imgP2.setSizePolicy(sizePolicy)
        self.imgP2.setMinimumSize(QtCore.QSize(200, 200))
        self.imgP2.setMaximumSize(QtCore.QSize(200, 200))
        self.imgP2.setStyleSheet("border-image: url(:/ui/img/placeholder_head.jpg);")
        self.imgP2.setObjectName("imgP2")
        self.horizontalLayout_6.addWidget(self.imgP2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.lblP2 = QtWidgets.QLabel(self.widgetLayoutP2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblP2.sizePolicy().hasHeightForWidth())
        self.lblP2.setSizePolicy(sizePolicy)
        self.lblP2.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblP2.setFont(font)
        self.lblP2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblP2.setWordWrap(True)
        self.lblP2.setObjectName("lblP2")
        self.verticalLayout_11.addWidget(self.lblP2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.layoutP1P2.addWidget(self.widgetLayoutP2)
        self.horizontalLayout.addLayout(self.layoutP1P2)
        spacerItem4 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        spacerItem5 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.layoutP1P2_3 = QtWidgets.QVBoxLayout()
        self.layoutP1P2_3.setObjectName("layoutP1P2_3")
        self.widgetLayoutP3 = QtWidgets.QWidget(Form)
        self.widgetLayoutP3.setObjectName("widgetLayoutP3")
        self.layoutP1_6 = QtWidgets.QHBoxLayout(self.widgetLayoutP3)
        self.layoutP1_6.setObjectName("layoutP1_6")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutP1_6.addItem(spacerItem6)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.imgP3 = QtWidgets.QWidget(self.widgetLayoutP3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgP3.sizePolicy().hasHeightForWidth())
        self.imgP3.setSizePolicy(sizePolicy)
        self.imgP3.setMinimumSize(QtCore.QSize(200, 200))
        self.imgP3.setMaximumSize(QtCore.QSize(200, 200))
        self.imgP3.setStyleSheet("border-image: url(:/ui/img/placeholder_head.jpg);")
        self.imgP3.setObjectName("imgP3")
        self.horizontalLayout_7.addWidget(self.imgP3)
        self.verticalLayout_14.addLayout(self.horizontalLayout_7)
        self.lblP3 = QtWidgets.QLabel(self.widgetLayoutP3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblP3.sizePolicy().hasHeightForWidth())
        self.lblP3.setSizePolicy(sizePolicy)
        self.lblP3.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblP3.setFont(font)
        self.lblP3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblP3.setWordWrap(True)
        self.lblP3.setObjectName("lblP3")
        self.verticalLayout_14.addWidget(self.lblP3)
        self.layoutP1_6.addLayout(self.verticalLayout_14)
        self.layoutP1P2_3.addWidget(self.widgetLayoutP3)
        self.widgetLayoutP4 = QtWidgets.QWidget(Form)
        self.widgetLayoutP4.setObjectName("widgetLayoutP4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widgetLayoutP4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.imgP4 = QtWidgets.QWidget(self.widgetLayoutP4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imgP4.sizePolicy().hasHeightForWidth())
        self.imgP4.setSizePolicy(sizePolicy)
        self.imgP4.setMinimumSize(QtCore.QSize(200, 200))
        self.imgP4.setMaximumSize(QtCore.QSize(200, 200))
        self.imgP4.setStyleSheet("border-image: url(:/ui/img/placeholder_head.jpg);")
        self.imgP4.setObjectName("imgP4")
        self.horizontalLayout_9.addWidget(self.imgP4)
        self.verticalLayout_15.addLayout(self.horizontalLayout_9)
        self.lblP4 = QtWidgets.QLabel(self.widgetLayoutP4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblP4.sizePolicy().hasHeightForWidth())
        self.lblP4.setSizePolicy(sizePolicy)
        self.lblP4.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lblP4.setFont(font)
        self.lblP4.setAlignment(QtCore.Qt.AlignCenter)
        self.lblP4.setWordWrap(True)
        self.lblP4.setObjectName("lblP4")
        self.verticalLayout_15.addWidget(self.lblP4)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.layoutP1P2_3.addWidget(self.widgetLayoutP4)
        self.horizontalLayout.addLayout(self.layoutP1P2_3)
        spacerItem8 = QtWidgets.QSpacerItem(75, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Identify yourselves! "))
        self.label_6.setText(_translate("Form", "Use the table\'s RFID reader with your card."))
        self.lblP1.setText(_translate("Form", "Player 1"))
        self.lblP2.setText(_translate("Form", "Player 2"))
        self.label_7.setText(_translate("Form", "vs."))
        self.lblP3.setText(_translate("Form", "Player 3"))
        self.lblP4.setText(_translate("Form", "Player 4"))
from babyfut_server.ui import assets_rc
