# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/options.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        Form.setStyleSheet("QRadioButton {\n"
"    border: 2px solid rgb(74, 74, 107);\n"
"    border-radius: 10px;\n"
"    border-color: rgb(74, 74, 107);\n"
"}\n"
"\n"
"QRadioButton::checked {\n"
"    background-color: rgba(44, 44, 63, 240);\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    background-color: transparent;\n"
"    border: 0px solid transparent;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(15, 15, 15, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gbGameOver = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbGameOver.sizePolicy().hasHeightForWidth())
        self.gbGameOver.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.gbGameOver.setFont(font)
        self.gbGameOver.setAutoFillBackground(True)
        self.gbGameOver.setAlignment(QtCore.Qt.AlignCenter)
        self.gbGameOver.setObjectName("gbGameOver")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbGameOver)
        self.verticalLayout_2.setContentsMargins(-1, 40, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.rbGameOver_Score = QtWidgets.QRadioButton(self.gbGameOver)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbGameOver_Score.sizePolicy().hasHeightForWidth())
        self.rbGameOver_Score.setSizePolicy(sizePolicy)
        self.rbGameOver_Score.setMinimumSize(QtCore.QSize(280, 65))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.rbGameOver_Score.setFont(font)
        self.rbGameOver_Score.setCheckable(True)
        self.rbGameOver_Score.setObjectName("rbGameOver_Score")
        self.horizontalLayout.addWidget(self.rbGameOver_Score)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.rbGameOver_Time = QtWidgets.QRadioButton(self.gbGameOver)
        self.rbGameOver_Time.setMinimumSize(QtCore.QSize(280, 65))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.rbGameOver_Time.setFont(font)
        self.rbGameOver_Time.setObjectName("rbGameOver_Time")
        self.horizontalLayout.addWidget(self.rbGameOver_Time)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.sliderGameOverValue = QtWidgets.QSlider(self.gbGameOver)
        self.sliderGameOverValue.setMinimumSize(QtCore.QSize(0, 40))
        self.sliderGameOverValue.setMinimum(1)
        self.sliderGameOverValue.setMaximum(60)
        self.sliderGameOverValue.setProperty("value", 10)
        self.sliderGameOverValue.setOrientation(QtCore.Qt.Horizontal)
        self.sliderGameOverValue.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.sliderGameOverValue.setTickInterval(5)
        self.sliderGameOverValue.setObjectName("sliderGameOverValue")
        self.horizontalLayout_2.addWidget(self.sliderGameOverValue)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.lblGameOverValue = QtWidgets.QLabel(self.gbGameOver)
        self.lblGameOverValue.setMinimumSize(QtCore.QSize(150, 0))
        self.lblGameOverValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGameOverValue.setObjectName("lblGameOverValue")
        self.horizontalLayout_2.addWidget(self.lblGameOverValue)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.gbGameOver)
        self.gbLeaguePlayers = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbLeaguePlayers.sizePolicy().hasHeightForWidth())
        self.gbLeaguePlayers.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.gbLeaguePlayers.setFont(font)
        self.gbLeaguePlayers.setAutoFillBackground(True)
        self.gbLeaguePlayers.setAlignment(QtCore.Qt.AlignCenter)
        self.gbLeaguePlayers.setObjectName("gbLeaguePlayers")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gbLeaguePlayers)
        self.horizontalLayout_4.setContentsMargins(-1, 40, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.rbNumPlayerLeague_1 = QtWidgets.QRadioButton(self.gbLeaguePlayers)
        self.rbNumPlayerLeague_1.setMinimumSize(QtCore.QSize(280, 65))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.rbNumPlayerLeague_1.setFont(font)
        self.rbNumPlayerLeague_1.setObjectName("rbNumPlayerLeague_1")
        self.horizontalLayout_4.addWidget(self.rbNumPlayerLeague_1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.rbNumPlayerLeague_2 = QtWidgets.QRadioButton(self.gbLeaguePlayers)
        self.rbNumPlayerLeague_2.setMinimumSize(QtCore.QSize(280, 65))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.rbNumPlayerLeague_2.setFont(font)
        self.rbNumPlayerLeague_2.setObjectName("rbNumPlayerLeague_2")
        self.horizontalLayout_4.addWidget(self.rbNumPlayerLeague_2)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.gbLeaguePlayers)
        self.gbLanguage = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbLanguage.sizePolicy().hasHeightForWidth())
        self.gbLanguage.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.gbLanguage.setFont(font)
        self.gbLanguage.setAlignment(QtCore.Qt.AlignCenter)
        self.gbLanguage.setObjectName("gbLanguage")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbLanguage)
        self.horizontalLayout_3.setContentsMargins(-1, 40, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.rbLanguage_English = QtWidgets.QRadioButton(self.gbLanguage)
        self.rbLanguage_English.setMinimumSize(QtCore.QSize(280, 65))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.rbLanguage_English.setFont(font)
        self.rbLanguage_English.setObjectName("rbLanguage_English")
        self.horizontalLayout_3.addWidget(self.rbLanguage_English)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.rbLanguage_French = QtWidgets.QRadioButton(self.gbLanguage)
        self.rbLanguage_French.setMinimumSize(QtCore.QSize(280, 65))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.rbLanguage_French.setFont(font)
        self.rbLanguage_French.setObjectName("rbLanguage_French")
        self.horizontalLayout_3.addWidget(self.rbLanguage_French)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.verticalLayout.addWidget(self.gbLanguage)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.rbGameOver_Score, self.rbGameOver_Time)
        Form.setTabOrder(self.rbGameOver_Time, self.sliderGameOverValue)
        Form.setTabOrder(self.sliderGameOverValue, self.rbNumPlayerLeague_1)
        Form.setTabOrder(self.rbNumPlayerLeague_1, self.rbNumPlayerLeague_2)
        Form.setTabOrder(self.rbNumPlayerLeague_2, self.rbLanguage_English)
        Form.setTabOrder(self.rbLanguage_English, self.rbLanguage_French)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Options"))
        self.gbGameOver.setTitle(_translate("Form", "Game Over Condition"))
        self.rbGameOver_Score.setText(_translate("Form", "By Score"))
        self.rbGameOver_Time.setText(_translate("Form", "By Time"))
        self.lblGameOverValue.setText(_translate("Form", "{} minutes"))
        self.gbLeaguePlayers.setTitle(_translate("Form", "League - Number of players per side"))
        self.rbNumPlayerLeague_1.setText(_translate("Form", "1"))
        self.rbNumPlayerLeague_2.setText(_translate("Form", "2"))
        self.gbLanguage.setTitle(_translate("Form", "Language"))
        self.rbLanguage_English.setText(_translate("Form", "English"))
        self.rbLanguage_French.setText(_translate("Form", "Français"))
from babyfut_server.ui import assets_rc
