# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/playerlist.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1270, 150)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.picHolder = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.picHolder.sizePolicy().hasHeightForWidth())
        self.picHolder.setSizePolicy(sizePolicy)
        self.picHolder.setMinimumSize(QtCore.QSize(125, 125))
        self.picHolder.setStyleSheet("border-image: url(:/ui/img/placeholder_head.jpg);")
        self.picHolder.setObjectName("picHolder")
        self.horizontalLayout.addWidget(self.picHolder)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblLName = QtWidgets.QLabel(Form)
        self.lblLName.setMinimumSize(QtCore.QSize(200, 0))
        self.lblLName.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lblLName.setFont(font)
        self.lblLName.setObjectName("lblLName")
        self.verticalLayout.addWidget(self.lblLName)
        self.lblFName = QtWidgets.QLabel(Form)
        self.lblFName.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lblFName.setFont(font)
        self.lblFName.setObjectName("lblFName")
        self.verticalLayout.addWidget(self.lblFName)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.lblVictories = QtWidgets.QLabel(Form)
        self.lblVictories.setObjectName("lblVictories")
        self.horizontalLayout.addWidget(self.lblVictories)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.lblGoalsScored = QtWidgets.QLabel(Form)
        self.lblGoalsScored.setObjectName("lblGoalsScored")
        self.horizontalLayout.addWidget(self.lblGoalsScored)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.lblGamesPlayed = QtWidgets.QLabel(Form)
        self.lblGamesPlayed.setObjectName("lblGamesPlayed")
        self.horizontalLayout.addWidget(self.lblGamesPlayed)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.lblMinutesPlayed = QtWidgets.QLabel(Form)
        self.lblMinutesPlayed.setObjectName("lblMinutesPlayed")
        self.horizontalLayout.addWidget(self.lblMinutesPlayed)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ui/img/icons/red-cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblLName.setText(_translate("Form", "Name"))
        self.lblFName.setText(_translate("Form", "Surname"))
        self.lblVictories.setText(_translate("Form", "{} Victories", "Form"))
        self.lblGoalsScored.setText(_translate("Form", "{} Goals Scored", "Form"))
        self.lblGamesPlayed.setText(_translate("Form", "{} Games Played", "Form"))
        self.lblMinutesPlayed.setText(_translate("Form", "{} Minutes Played", "Form"))
from babyfut_server.ui import assets_rc
