from .authquick   import AuthQuickModule
from .authleague  import AuthLeagueModule
from .game        import GameModule
from .endgame     import EndGameModule
from .menu        import MenuModule
from .options     import OptionsModule
from .leaderboard import LeaderboardModule
from .privacy     import PrivacyModule
from .edit        import EditModule
